// <auto-generated />
using System;
using Estimation.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Estimation.Core.Migrations
{
    [DbContext(typeof(EstimationDbContext))]
    [Migration("20260512184734_AddBackupSettingsAndHistory")]
    partial class AddBackupSettingsAndHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Estimation.Core.JiraLogic.JiraToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("AccessTokenSecret")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("JiraTokens");
                });

            modelBuilder.Entity("Estimation.Core.Models.AppPage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Group")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsAdminOnly")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("AppPages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayName = "Dashboard",
                            IsAdminOnly = false,
                            Key = "Dashboard",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 2,
                            DisplayName = "PI",
                            Group = "Planning Increment",
                            IsAdminOnly = false,
                            Key = "Pis",
                            SortOrder = 10
                        },
                        new
                        {
                            Id = 3,
                            DisplayName = "Prioritization",
                            Group = "Planning Increment",
                            IsAdminOnly = false,
                            Key = "PiPrioritization",
                            SortOrder = 11
                        },
                        new
                        {
                            Id = 5,
                            DisplayName = "Solution Trains",
                            Group = "Planning",
                            IsAdminOnly = false,
                            Key = "CapitalProjects",
                            SortOrder = 20
                        },
                        new
                        {
                            Id = 6,
                            DisplayName = "Strategic Objectives",
                            Group = "Planning",
                            IsAdminOnly = false,
                            Key = "StrategicObjectives",
                            SortOrder = 22
                        },
                        new
                        {
                            Id = 7,
                            DisplayName = "Portfolio Epics",
                            Group = "Planning",
                            IsAdminOnly = false,
                            Key = "PortfolioEpics",
                            SortOrder = 23
                        },
                        new
                        {
                            Id = 8,
                            DisplayName = "Business Outcomes",
                            Group = "Planning",
                            IsAdminOnly = false,
                            Key = "BusinessOutcomes",
                            SortOrder = 24
                        },
                        new
                        {
                            Id = 9,
                            DisplayName = "Features",
                            Group = "Planning",
                            IsAdminOnly = false,
                            Key = "Features",
                            SortOrder = 25
                        },
                        new
                        {
                            Id = 10,
                            DisplayName = "Teams",
                            Group = "Resources",
                            IsAdminOnly = false,
                            Key = "Teams",
                            SortOrder = 30
                        },
                        new
                        {
                            Id = 11,
                            DisplayName = "Resources",
                            Group = "Resources",
                            IsAdminOnly = false,
                            Key = "HumanResources",
                            SortOrder = 31
                        },
                        new
                        {
                            Id = 12,
                            DisplayName = "Skills",
                            Group = "Resources",
                            IsAdminOnly = false,
                            Key = "Skills",
                            SortOrder = 32
                        },
                        new
                        {
                            Id = 13,
                            DisplayName = "Technology Stacks",
                            Group = "Resources",
                            IsAdminOnly = false,
                            Key = "TechnologyStacks",
                            SortOrder = 33
                        },
                        new
                        {
                            Id = 14,
                            DisplayName = "Audit Log",
                            Group = "Admin",
                            IsAdminOnly = true,
                            Key = "AuditLog",
                            SortOrder = 90
                        },
                        new
                        {
                            Id = 15,
                            DisplayName = "Static Data",
                            Group = "Admin",
                            IsAdminOnly = true,
                            Key = "StaticSettings",
                            SortOrder = 91
                        },
                        new
                        {
                            Id = 16,
                            DisplayName = "Authorization",
                            Group = "Admin",
                            IsAdminOnly = true,
                            Key = "Authorization",
                            SortOrder = 92
                        },
                        new
                        {
                            Id = 17,
                            DisplayName = "Database Backup",
                            Group = "Admin",
                            IsAdminOnly = true,
                            Key = "DatabaseBackup",
                            SortOrder = 93
                        });
                });

            modelBuilder.Entity("Estimation.Core.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsAccessRequested")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("RequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("WindowsUserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("WindowsUserName")
                        .IsUnique();

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("Estimation.Core.Models.AppUserPagePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessLevel")
                        .HasColumnType("int");

                    b.Property<int>("AppPageId")
                        .HasColumnType("int");

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AppPageId");

                    b.HasIndex("AppUserId", "AppPageId")
                        .IsUnique();

                    b.ToTable("AppUserPagePermissions");
                });

            modelBuilder.Entity("Estimation.Core.Models.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PropertyName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("EntityName");

                    b.HasIndex("Timestamp");

                    b.HasIndex("EntityName", "EntityId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Estimation.Core.Models.BackupHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FilePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TriggeredBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt");

                    b.ToTable("BackupHistory");
                });

            modelBuilder.Entity("Estimation.Core.Models.BackupSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BackupFolderPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<TimeSpan>("DailyTime")
                        .HasColumnType("time");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<int>("IntervalHours")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastBackupAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NextBackupAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RetentionCount")
                        .HasColumnType("int");

                    b.Property<int>("ScheduleType")
                        .HasColumnType("int");

                    b.Property<int>("WeeklyDay")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("BackupSettings");
                });

            modelBuilder.Entity("Estimation.Core.Models.BusinessOutcome", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArtName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Comments")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Description")
                        .HasMaxLength(32767)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IssueType")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("JiraId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("JiraUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Labels")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int?>("PortfolioEpicId")
                        .HasColumnType("int");

                    b.Property<string>("ProjectKey")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("Ranking")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("StoryPoints")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("TargetEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TargetStart")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ArtName");

                    b.HasIndex("PortfolioEpicId");

                    b.HasIndex("Ranking");

                    b.ToTable("BusinessOutcomes");
                });

            modelBuilder.Entity("Estimation.Core.Models.CapitalProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("JiraKey")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("CapitalProjects");
                });

            modelBuilder.Entity("Estimation.Core.Models.CapitalProjectStrategicObjective", b =>
                {
                    b.Property<int>("CapitalProjectId")
                        .HasColumnType("int");

                    b.Property<int>("StrategicObjectiveId")
                        .HasColumnType("int");

                    b.HasKey("CapitalProjectId", "StrategicObjectiveId");

                    b.HasIndex("StrategicObjectiveId");

                    b.ToTable("CapitalProjectStrategicObjectives", (string)null);
                });

            modelBuilder.Entity("Estimation.Core.Models.CapitalProjectTeam", b =>
                {
                    b.Property<int>("CapitalProjectId")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("CapitalProjectId", "TeamId");

                    b.HasIndex("TeamId");

                    b.ToTable("CapitalProjectTeams");
                });

            modelBuilder.Entity("Estimation.Core.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("Id");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("Estimation.Core.Models.CorporateGrade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("CorporateGrades");
                });

            modelBuilder.Entity("Estimation.Core.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("Id");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("Estimation.Core.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("Estimation.Core.Models.EmployeeCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("EmployeeCategories");
                });

            modelBuilder.Entity("Estimation.Core.Models.EmployeeRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("EmployeeRoles");
                });

            modelBuilder.Entity("Estimation.Core.Models.EmployeeType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("EmployeeTypes");
                });

            modelBuilder.Entity("Estimation.Core.Models.EmployeeVendor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("EmployeeVendors");
                });

            modelBuilder.Entity("Estimation.Core.Models.Feature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BusinessOutcomeId")
                        .HasColumnType("int");

                    b.Property<string>("Comments")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("DateExpected")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(32767)
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsLinkedToTheJira")
                        .HasColumnType("bit");

                    b.Property<string>("IssueType")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("JiraId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("JiraUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Labels")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("PiId")
                        .HasColumnType("int");

                    b.Property<string>("ProjectKey")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("Ranking")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("StoryPoints")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("TargetEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TargetStart")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UnfundedOptionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BusinessOutcomeId");

                    b.HasIndex("JiraId");

                    b.HasIndex("Name");

                    b.HasIndex("PiId");

                    b.HasIndex("ProjectKey");

                    b.HasIndex("Ranking");

                    b.HasIndex("UnfundedOptionId");

                    b.ToTable("Features");
                });

            modelBuilder.Entity("Estimation.Core.Models.FeatureTeam", b =>
                {
                    b.Property<int>("FeatureId")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("FeatureId", "TeamId");

                    b.HasIndex("TeamId");

                    b.ToTable("FeatureTeams");
                });

            modelBuilder.Entity("Estimation.Core.Models.FeatureTechnologyStack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("EstimatedEffort")
                        .HasColumnType("int");

                    b.Property<int>("FeatureId")
                        .HasColumnType("int");

                    b.Property<int>("TechnologyStackId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FeatureId");

                    b.HasIndex("TechnologyStackId");

                    b.HasIndex("FeatureId", "TechnologyStackId");

                    b.ToTable("FeatureTechnologyStacks");
                });

            modelBuilder.Entity("Estimation.Core.Models.HumanResource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cio")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Cio1")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Cio2")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<int?>("CorporateGradeId")
                        .HasColumnType("int");

                    b.Property<int?>("CountryId")
                        .HasColumnType("int");

                    b.Property<int?>("EmployeeCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("EmployeeNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("EmployeeRoleId")
                        .HasColumnType("int");

                    b.Property<int?>("EmployeeTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("EmployeeVendorId")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LineManagerName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("TeamRoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("CorporateGradeId");

                    b.HasIndex("CountryId");

                    b.HasIndex("EmployeeCategoryId");

                    b.HasIndex("EmployeeName");

                    b.HasIndex("EmployeeNumber");

                    b.HasIndex("EmployeeRoleId");

                    b.HasIndex("EmployeeTypeId");

                    b.HasIndex("EmployeeVendorId");

                    b.HasIndex("FullName");

                    b.HasIndex("IsActive");

                    b.HasIndex("TeamRoleId");

                    b.ToTable("HumanResources");
                });

            modelBuilder.Entity("Estimation.Core.Models.HumanResourceSkill", b =>
                {
                    b.Property<int>("HumanResourceId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<int?>("SkillLevelId")
                        .HasColumnType("int");

                    b.HasKey("HumanResourceId", "SkillId");

                    b.HasIndex("HumanResourceId");

                    b.HasIndex("SkillId");

                    b.HasIndex("SkillLevelId");

                    b.ToTable("HumanResourceSkills");
                });

            modelBuilder.Entity("Estimation.Core.Models.Pi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comments")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Priority")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Pis");
                });

            modelBuilder.Entity("Estimation.Core.Models.PortfolioEpic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comments")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Description")
                        .HasMaxLength(32767)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IssueType")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("JiraId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("JiraUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Labels")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("ProjectKey")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("Ranking")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("StoryPoints")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("TargetEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TargetStart")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("PortfolioEpics");
                });

            modelBuilder.Entity("Estimation.Core.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Created")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("Estimation.Core.Models.SkillLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("SkillId")
                        .HasColumnType("int");

                    b.Property<int?>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.ToTable("SkillLevels");
                });

            modelBuilder.Entity("Estimation.Core.Models.StrategicObjective", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comments")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Description")
                        .HasMaxLength(32767)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IssueType")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("JiraId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("JiraUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Labels")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("ProjectKey")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("StoryPoints")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("TargetEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TargetStart")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("StrategicObjectives", (string)null);
                });

            modelBuilder.Entity("Estimation.Core.Models.StrategicObjectivePortfolioEpic", b =>
                {
                    b.Property<int>("StrategicObjectiveId")
                        .HasColumnType("int");

                    b.Property<int>("PortfolioEpicId")
                        .HasColumnType("int");

                    b.HasKey("StrategicObjectiveId", "PortfolioEpicId");

                    b.HasIndex("PortfolioEpicId");

                    b.ToTable("StrategicObjectivePortfolioEpics", (string)null);
                });

            modelBuilder.Entity("Estimation.Core.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FullName")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OptionalTeamTag")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("Estimation.Core.Models.TeamMember", b =>
                {
                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<int>("HumanResourceId")
                        .HasColumnType("int");

                    b.HasKey("TeamId", "HumanResourceId");

                    b.HasIndex("HumanResourceId");

                    b.ToTable("TeamMembers");
                });

            modelBuilder.Entity("Estimation.Core.Models.TeamRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TeamRoles");
                });

            modelBuilder.Entity("Estimation.Core.Models.TeamTechnologyStack", b =>
                {
                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<int>("TechnologyStackId")
                        .HasColumnType("int");

                    b.HasKey("TeamId", "TechnologyStackId");

                    b.HasIndex("TechnologyStackId");

                    b.ToTable("TeamTechnologyStacks");
                });

            modelBuilder.Entity("Estimation.Core.Models.TechnologyStack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("TechnologyStacks");
                });

            modelBuilder.Entity("Estimation.Core.Models.TechnologyStackSkill", b =>
                {
                    b.Property<int>("TechnologyStackId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.HasKey("TechnologyStackId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("TechnologyStackSkills");
                });

            modelBuilder.Entity("Estimation.Core.Models.UnfundedOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UnfundedOptions");
                });

            modelBuilder.Entity("Estimation.Core.Models.AppUserPagePermission", b =>
                {
                    b.HasOne("Estimation.Core.Models.AppPage", "AppPage")
                        .WithMany()
                        .HasForeignKey("AppPageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Estimation.Core.Models.AppUser", "AppUser")
                        .WithMany("PagePermissions")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppPage");

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("Estimation.Core.Models.BusinessOutcome", b =>
                {
                    b.HasOne("Estimation.Core.Models.PortfolioEpic", "PortfolioEpic")
                        .WithMany("BusinessOutcomes")
                        .HasForeignKey("PortfolioEpicId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PortfolioEpic");
                });

            modelBuilder.Entity("Estimation.Core.Models.CapitalProject", b =>
                {
                    b.HasOne("Estimation.Core.Models.Department", "Department")
                        .WithMany("CapitalProjects")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Estimation.Core.Models.CapitalProjectStrategicObjective", b =>
                {
                    b.HasOne("Estimation.Core.Models.CapitalProject", "CapitalProject")
                        .WithMany("CapitalProjectStrategicObjectives")
                        .HasForeignKey("CapitalProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Estimation.Core.Models.StrategicObjective", "StrategicObjective")
                        .WithMany("CapitalProjectStrategicObjectives")
                        .HasForeignKey("StrategicObjectiveId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CapitalProject");

                    b.Navigation("StrategicObjective");
                });

            modelBuilder.Entity("Estimation.Core.Models.CapitalProjectTeam", b =>
                {
                    b.HasOne("Estimation.Core.Models.CapitalProject", "CapitalProject")
                        .WithMany("CapitalProjectTeams")
                        .HasForeignKey("CapitalProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Estimation.Core.Models.Team", "Team")
                        .WithMany("CapitalProjectTeams")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CapitalProject");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Estimation.Core.Models.Feature", b =>
                {
                    b.HasOne("Estimation.Core.Models.BusinessOutcome", "BusinessOutcome")
                        .WithMany("Features")
                        .HasForeignKey("BusinessOutcomeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Estimation.Core.Models.Pi", "Pi")
                        .WithMany("Features")
                        .HasForeignKey("PiId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Estimation.Core.Models.UnfundedOption", "UnfundedOption")
                        .WithMany("Features")
                        .HasForeignKey("UnfundedOptionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BusinessOutcome");

                    b.Navigation("Pi");

                    b.Navigation("UnfundedOption");
                });

            modelBuilder.Entity("Estimation.Core.Models.FeatureTeam", b =>
                {
                    b.HasOne("Estimation.Core.Models.Feature", "Feature")
                        .WithMany("FeatureTeams")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Estimation.Core.Models.Team", "Team")
                        .WithMany("FeatureTeams")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Feature");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Estimation.Core.Models.FeatureTechnologyStack", b =>
                {
                    b.HasOne("Estimation.Core.Models.Feature", "Feature")
                        .WithMany("FeatureTechnologyStacks")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Estimation.Core.Models.TechnologyStack", "TechnologyStack")
                        .WithMany("FeatureTechnologyStacks")
                        .HasForeignKey("TechnologyStackId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Feature");

                    b.Navigation("TechnologyStack");
                });

            modelBuilder.Entity("Estimation.Core.Models.HumanResource", b =>
                {
                    b.HasOne("Estimation.Core.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Estimation.Core.Models.CorporateGrade", "CorporateGrade")
                        .WithMany()
                        .HasForeignKey("CorporateGradeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Estimation.Core.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Estimation.Core.Models.EmployeeCategory", "EmployeeCategory")
                        .WithMany()
                        .HasForeignKey("EmployeeCategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Estimation.Core.Models.EmployeeRole", "EmployeeRole")
                        .WithMany()
                        .HasForeignKey("EmployeeRoleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Estimation.Core.Models.EmployeeType", "EmployeeType")
                        .WithMany()
                        .HasForeignKey("EmployeeTypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Estimation.Core.Models.EmployeeVendor", "EmployeeVendor")
                        .WithMany()
                        .HasForeignKey("EmployeeVendorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Estimation.Core.Models.TeamRole", "TeamRole")
                        .WithMany()
                        .HasForeignKey("TeamRoleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("City");

                    b.Navigation("CorporateGrade");

                    b.Navigation("Country");

                    b.Navigation("EmployeeCategory");

                    b.Navigation("EmployeeRole");

                    b.Navigation("EmployeeType");

                    b.Navigation("EmployeeVendor");

                    b.Navigation("TeamRole");
                });

            modelBuilder.Entity("Estimation.Core.Models.HumanResourceSkill", b =>
                {
                    b.HasOne("Estimation.Core.Models.HumanResource", "HumanResource")
                        .WithMany("HumanResourceSkills")
                        .HasForeignKey("HumanResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Estimation.Core.Models.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Estimation.Core.Models.SkillLevel", "SkillLevel")
                        .WithMany()
                        .HasForeignKey("SkillLevelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("HumanResource");

                    b.Navigation("Skill");

                    b.Navigation("SkillLevel");
                });

            modelBuilder.Entity("Estimation.Core.Models.SkillLevel", b =>
                {
                    b.HasOne("Estimation.Core.Models.Skill", null)
                        .WithMany("Levels")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Estimation.Core.Models.StrategicObjectivePortfolioEpic", b =>
                {
                    b.HasOne("Estimation.Core.Models.PortfolioEpic", "PortfolioEpic")
                        .WithMany("StrategicObjectivePortfolioEpics")
                        .HasForeignKey("PortfolioEpicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Estimation.Core.Models.StrategicObjective", "StrategicObjective")
                        .WithMany("StrategicObjectivePortfolioEpics")
                        .HasForeignKey("StrategicObjectiveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PortfolioEpic");

                    b.Navigation("StrategicObjective");
                });

            modelBuilder.Entity("Estimation.Core.Models.TeamMember", b =>
                {
                    b.HasOne("Estimation.Core.Models.HumanResource", "HumanResource")
                        .WithMany("TeamMembers")
                        .HasForeignKey("HumanResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Estimation.Core.Models.Team", "Team")
                        .WithMany("TeamMembers")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HumanResource");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Estimation.Core.Models.TeamTechnologyStack", b =>
                {
                    b.HasOne("Estimation.Core.Models.Team", "Team")
                        .WithMany("TeamTechnologyStacks")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Estimation.Core.Models.TechnologyStack", "TechnologyStack")
                        .WithMany("TeamTechnologyStacks")
                        .HasForeignKey("TechnologyStackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("TechnologyStack");
                });

            modelBuilder.Entity("Estimation.Core.Models.TechnologyStackSkill", b =>
                {
                    b.HasOne("Estimation.Core.Models.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Estimation.Core.Models.TechnologyStack", "TechnologyStack")
                        .WithMany("TechnologyStackSkills")
                        .HasForeignKey("TechnologyStackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");

                    b.Navigation("TechnologyStack");
                });

            modelBuilder.Entity("Estimation.Core.Models.AppUser", b =>
                {
                    b.Navigation("PagePermissions");
                });

            modelBuilder.Entity("Estimation.Core.Models.BusinessOutcome", b =>
                {
                    b.Navigation("Features");
                });

            modelBuilder.Entity("Estimation.Core.Models.CapitalProject", b =>
                {
                    b.Navigation("CapitalProjectStrategicObjectives");

                    b.Navigation("CapitalProjectTeams");
                });

            modelBuilder.Entity("Estimation.Core.Models.Department", b =>
                {
                    b.Navigation("CapitalProjects");
                });

            modelBuilder.Entity("Estimation.Core.Models.Feature", b =>
                {
                    b.Navigation("FeatureTeams");

                    b.Navigation("FeatureTechnologyStacks");
                });

            modelBuilder.Entity("Estimation.Core.Models.HumanResource", b =>
                {
                    b.Navigation("HumanResourceSkills");

                    b.Navigation("TeamMembers");
                });

            modelBuilder.Entity("Estimation.Core.Models.Pi", b =>
                {
                    b.Navigation("Features");
                });

            modelBuilder.Entity("Estimation.Core.Models.PortfolioEpic", b =>
                {
                    b.Navigation("BusinessOutcomes");

                    b.Navigation("StrategicObjectivePortfolioEpics");
                });

            modelBuilder.Entity("Estimation.Core.Models.Skill", b =>
                {
                    b.Navigation("Levels");
                });

            modelBuilder.Entity("Estimation.Core.Models.StrategicObjective", b =>
                {
                    b.Navigation("CapitalProjectStrategicObjectives");

                    b.Navigation("StrategicObjectivePortfolioEpics");
                });

            modelBuilder.Entity("Estimation.Core.Models.Team", b =>
                {
                    b.Navigation("CapitalProjectTeams");

                    b.Navigation("FeatureTeams");

                    b.Navigation("TeamMembers");

                    b.Navigation("TeamTechnologyStacks");
                });

            modelBuilder.Entity("Estimation.Core.Models.TechnologyStack", b =>
                {
                    b.Navigation("FeatureTechnologyStacks");

                    b.Navigation("TeamTechnologyStacks");

                    b.Navigation("TechnologyStackSkills");
                });

            modelBuilder.Entity("Estimation.Core.Models.UnfundedOption", b =>
                {
                    b.Navigation("Features");
                });
#pragma warning restore 612, 618
        }
    }
}
